#!/bin/bash -e
if [ ! -d "/storage" ]; then
    echo "We need a place to store and share persistent data. Please recreate this "
    echo "container using docker -v parameter like this:"
    echo ""
    echo "  docker -v {your local storage directory}:/storage:rw,z ......"
    echo ""
    exit 1
fi

#define our service and home directories and setup permissions
mkdir -p            /storage/home /storage/loginbox/etc/ssh
chown root:root     /storage/home /storage 
chmod 755           /storage/home /storage/loginbox
chmod 701           /storage
chmod u+s           /bin/ping /bin/ping6
chmod 600           /storage/initialconfig.yaml
rm -rf              /home
ln -s               /storage/home /home
ln -fs              /storage/root/.zsh_history /root/.zsh_history

#create fresh keys if they don't exist
if [ ! -f "/storage/loginbox/etc/ssh/ssh_host_rsa_key" ]; then

    ssh-keygen -f "/storage/loginbox/etc/ssh/ssh_host_rsa_key" -N "" -t rsa
    ssh-keygen -f "/storage/loginbox/etc/ssh/ssh_host_ed25519_key" -N "" -t ed25519
    ssh-keygen -f "/storage/loginbox/etc/ssh/ssh_host_ecdsa_key" -N "" -t ecdsa
    echo -ne "\nPermitRootLogin no\nAllowGroups ssh-users\n" >> /etc/ssh/sshd_config
fi
ln -fs /storage/loginbox/etc/ssh/ssh_host_rsa_key* /etc/ssh
ln -fs /storage/loginbox/etc/ssh/ssh_host_ed25519_key* /etc/ssh
ln -fs /storage/loginbox/etc/ssh/ssh_host_ecdsa_key* /etc/ssh

#start services
syslogd -C128 -t
service cron start
service anacron start
service nscd start
service xrdp start
service ssh start

#wait forever
while true; do sleep 60s; done;
