#!/bin/bash -e
if [ ! -d "/storage" ]; then
    echo "We need a place to store and share persistent data. Please recreate this "
    echo "container using docker -v parameter like this:"
    echo ""
    echo "  docker -v {your local storage directory}:/storage:rw,z ......"
    echo ""
    exit 1
fi

#define our service and home directories and setup permissions
mkdir -p            /storage/home 
chown root:root     /storage/home /storage 
chmod 755           /storage/home /storage
chmod 701           /storage
chmod u+s           /bin/ping /bin/ping6
chmod 600           /storage/initialconfig.yaml
rm -rf              /home
ln -s               /storage/home /home
ln -fs              /storage/samba/etc/smb.conf /etc/samba/smb.conf
ln -fs              /storage/root/.zsh_history /root/.zsh_history
smbpasswd -w "$(cat /storage/ldap/etc/libnss-ldap.secret)"

#start services
syslogd -C128 -t
service cron start
service anacron start
service nscd start
service smbd start
service nmbd start
populate-samba.py

#wait forever
while true; do sleep 60s; done;
