FROM lilwharfie_base:armhf
MAINTAINER Florian Reck
ENV DEBIAN_FRONTEND=noninteractive

#install necessary packages
RUN apt-get -qy update
RUN apt-get -qy upgrade
RUN apt-get -yq install python3-ldap python3-yaml lighttpd php-cgi php-curl php-gd php-pear  php-intl libphp-phpmailer php-sabre-dav php-simplexml php-zip php-gd php-curl php-mysqlnd php-sqlite3 php-mysqlnd mariadb-server mariadb-client php-redis php-redis redis-server redis-tools smbclient unzip php-mbstring php-seclib php-pimple php-apcu php-smbclient
ADD etc/docker-init.d /etc/docker-init.d
ADD etc/lighttpd /etc/lighttpd


# copy necessary scripts 
COPY usr/local/bin/* /usr/local/bin/

# clean up and create entrypoint
RUN apt-get -yq clean
ENV TERM=xterm
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
RUN localedef -i en_US -f UTF-8 en_US.UTF-8
WORKDIR /root
COPY etc/dockerinit /etc/
RUN chmod 744 /etc/dockerinit
ENTRYPOINT /etc/dockerinit
