#!/bin/bash -e
source /etc/profile
if [ ! -d "/storage" ]; then
    echo "We need a place to store and share persistent data. Please recreate this "
    echo "container using docker -v parameter like this:"
    echo ""
    echo "  docker -v {your local storage directory}:/storage:rw,z ......"
    echo ""
    exit 1
fi

#upgrade
apt-get -yq update
apt-get -yq full-upgrade

#start services
syslogd -C128 -t
setup-dnsmasq
service cron start
service anacron start
service unbound start
service dnsmasq start

#wait forever
while true; do sleep 60s; done;
