#!/bin/bash -e
source /etc/profile
if [ ! -d "/storage" ]; then
    echo "We need a place to store and share persistent data. Please recreate this "
    echo "container using docker -v parameter like this:"
    echo ""
    echo "  docker -v {your local storage directory}:/storage:rw,z ......"
    echo ""
    exit 1
fi

#preconfigure
if [ ! -d "/storage/dhcp" ]; then
    mkdir -p /storage/dhcp
    touch /storage/dhcp/custom_config
    touch /storage/dhcp/additional_hosts
    ln -s /storage/dhcp/custom_config /etc/dnsmasq.d/custom_config
    sync
fi;

#start services
syslogd -C128 -t
setup-dnsmasq

service cron start
service anacron start
service unbound start
service dnsmasq start
doh-server -conf /etc/dns-over-https/doh-server.conf
