#!/bin/bash -e
source /etc/profile

if [ ! -d "/storage" ]; then
    echo "We need a place to store and share persistent data. Please recreate this "
    echo "container using docker -v parameter like this:"
    echo ""
    echo "  docker -v {your local storage directory}:/storage:rw,z ......"
    echo ""
    exit 1
fi

#define our service and home directories and setup permissions
mkdir -p            /storage/ldap/etc/ldap /storage/home /storage/samba/etc /storage/root
chown root:root     /storage/ldap /storage/home /storage /storage/initialconfig.yaml
chmod 755           /storage/ldap /storage/ldap/etc /storage/home /storage/samba/etc
chmod 701           /storage /storage/root
chmod u+s           /bin/ping /bin/ping6
chmod 600           /storage/initialconfig.yaml
rm -rf              /home
ln -s               /storage/home /home
ln -fs              /storage/root/.zsh_history /root/.zsh_history

#start services
syslogd -C128 -t
service cron start
service anacron start
service slapd start

if [ ! -z "$(find /storage/ldap/backup/* -maxdepth 0 -type d |sort |tail -n1)" ]; then
    restore-last-ldap

elif [ -f "/storage/initialconfig.yaml" ]; then
    initialsetup
    backup-ldap
fi;

cd /storage/ldap/etc
ln -fs libnss-ldap.conf pam_ldap.conf
ln -fs libnss-ldap.secret pam_ldap.secret
cp /etc/nsswitch.conf .
cd ..
:>ldap_preconfig.tar.gz
find etc -print0 |xargs -0 tar cvzf ldap_preconfig.tar.gz

#wait forever
while true; do sleep 60s; done;
