#!/bin/bash
source /etc/profile
if [ ! -d "/storage" ]; then
    echo "We need a place to store and share persistent data. Please recreate this "
    echo "container using docker -v parameter like this:"
    echo ""
    echo "  docker -v {your local storage directory}:/storage:rw,z ......"
    echo ""
    exit 1
fi

#define our service and home directories and setup permissions
rm -rf              /home
ln -fs              /storage/home /home
ln -fs              /storage/root/.zsh_history /root/.zsh_history

if [ ! -d "/storage/web" ]; then
    echo "creating /storage/web folder and move existing content"
    mkdir -p /storage/web/var/lib /storage/web/docroot
    mv /var/lib/mysql /storage/web/var/lib
    ln -fs /storage/web/var/lib/mysql /var/lib/mysql
    sync
    mv /opt/strichliste /storage/web/docroot/strichliste
fi;

echo "recreating MySQL symlinks"
rm -rf /var/lib/mysql
ln -fs /storage/web/var/lib/mysql /var/lib

rm -rf /srv
ln -fs /storage/web/docroot /srv
chown mysql:mysql /storage/web /storage/web/var/lib/mysql

#create lightty usable certificate from storage 
cat /storage/certificates/privkey.pem /storage/certificates/cert.pem > /etc/lighttpd/server.pem
chown www-data:www-data /etc/lighttpd/server.pem
chmod 660 /etc/lighttpd/server.pem

# set MySQL root password
if [ ! -f "/storage/web/.mysqlcreds" ]; then
    mysql_install_db
    passgen="$(dd if=/dev/urandom count=16 bs=32 2>/dev/null |tr -cd "[:alnum:]" |head -c 16)"
    echo "$passgen" > "/storage/web/.mysqlcreds"
    service mysql start
    mysqladmin -u root password "$passgen"
    chmod 600 "/storage/web/.mysqlcreds"
    mysql --user=root --password=$(cat /storage/web/.mysqlcreds) << EOF
	CREATE DATABASE strichliste;
	CREATE USER 'strichliste'@'localhost' IDENTIFIED BY '32YourPassWord42';
	GRANT ALL PRIVILEGES ON strichliste.* TO 'strichliste'@'localhost';
        GRANT SELECT ON *.* TO 'strichliste'@'localhost';
	FLUSH PRIVILEGES;
	COMMIT;
EOF
    cd /storage/web/docroot/strichliste
    php /usr/bin/composer update
    php bin/console doctrine:schema:create
fi;

#start main services
syslogd -C128 -t
service cron start
service anacron start
service mysql start
service lighttpd start


#wait forever
while true; do sleep 60s; done;
