#!/bin/bash
source /etc/profile
if [ ! -d "/storage" ]; then
    echo "We need a place to store and share persistent data. Please recreate this "
    echo "container using docker -v parameter like this:"
    echo ""
    echo "  docker -v {your local storage directory}:/storage:rw,z ......"
    echo ""
    exit 1
fi

#define our service and home directories and setup permissions
rm -rf              /home
ln -s               /storage/home /home
ln -fs              /storage/root/.zsh_history /root/.zsh_history

if [ ! -d "/storage/web" ]; then
    mkdir -p /storage/web/var/lib /storage/web/docroot /var/lib/mysql
    mv /var/lib/mysql /storage/web/var/lib
    mv /opt/strichliste /storage/web/docroot/strichliste
else
    rm -rf /var/lib/mysql
    ln -fs /storage/web/var/lib/mysql /var/lib
fi;

rm -rf /srv
ln -fs /storage/web/docroot /srv
find /storage/web -print0 |xargs -0 chown www-data:www-data
find /storage/web/var/lib/mysql -print0 |xargs -0 chown mysql:mysql

#create lightty usable certificate from storage 
cat /storage/certificates/privkey.pem /storage/certificates/cert.pem > /etc/lighttpd/server.pem
chown www-data:www-data /etc/lighttpd/server.pem
chmod 660 /etc/lighttpd/server.pem

# set MySQL root password
if [ ! -f "/storage/web/.mysqlcreds" ]; then
    rm -rf /opt/web/var/lib/mysql/*
    mysql_install_db
    passgen="$(dd if=/dev/urandom count=16 bs=32 2>/dev/null |tr -cd "[:alnum:]" |head -c 16)"
    echo "$passgen" > "/storage/web/.mysqlcreds"
    service mysql start
    mysqladmin -u root password "$passgen"
    chmod 600 "/storage/web/.mysqlcreds"
    mysql --user=root --password=$(cat /storage/web/.mysqlcreds) << EOF
    GRANT ALL PRIVILEGES ON *.* TO 'strichliste'@'localhost' IDENTIFIED BY '32YourPassWord42';
    GRANT SELECT ON *.* TO 'strichliste'@'localhost';
EOF
    mysql --user="strichliste" --password="32YourPassWord42" << EOF
    CREATE DATABASE strichliste;
    COMMIT;
EOF
    cd /storage/web/docroot/strichliste
    php bin/console doctrine:schema:create
fi;

#start main services
syslogd -C128 -t
service cron start
service anacron start
service redis-server start
service mysql start
service lighttpd start


#wait forever
while true; do sleep 60s; done;
